version: '3.1'

services:
  nginx:
    image: nginx:1.15.3
    container_name: nginx
    ports:
      - "41080:80"
    volumes: 
      - static:/opt/services/autocomplete_feature/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on: 
      - autocomplete_feature_app    

  postgresql:
    image: postgres:11
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always 

  autocomplete_feature_app:
    container_name: autocomplete_feature_app
    environment: 
      - Token=4506842971332712c6c795620edf99005b1e5d5f
    command: ./start.sh
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - static:/opt/services/autocomplete_feature/static
    restart: always
    depends_on: 
      - postgresql

volumes: 
  pgdata: {}
  static: {}
